server:
    port: 8181

logging:
    level:
        docker.compose.example: INFO
        org.springframework: INFO

spring:
    profiles:
        active: dev
    application:
        name: Docker Compose Example
        title: Docker Compose Example
        description: Spring Boot Docker Compose Simple Example
        message: Creation App with connection to the DB and PhpMyAdmin Client
        server : localhost
        port: 8181

    jackson:
        serialization.indent_output: true


    datasource:
        username: root # xampp - maria db on localhost connection
        url: jdbc:mysql://localhost:3306/demo_db?createDatabaseIfNotExist=true&ssl-mode=REQUIRED
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            dialect: org.hibernate.dialect.MySQLDialect
            hibernate:
                format_sql: true
                use_sql_comments: true
                highlight_sql: true
        show-sql: true
        open-in-view: false